/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsRootRouteImport } from './routes/playlists/root'
import { Route as PlaylistsCreateRouteImport } from './routes/playlists/create'
import { Route as PlaylistsIdRouteImport } from './routes/playlists/$id'
import { Route as PlaylistsEditIdRouteImport } from './routes/playlists/edit.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRootRoute = PlaylistsRootRouteImport.update({
  id: '/playlists/root',
  path: '/playlists/root',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsCreateRoute = PlaylistsCreateRouteImport.update({
  id: '/playlists/create',
  path: '/playlists/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsEditIdRoute = PlaylistsEditIdRouteImport.update({
  id: '/playlists/edit/$id',
  path: '/playlists/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/create': typeof PlaylistsCreateRoute
  '/playlists/root': typeof PlaylistsRootRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/playlists/edit/$id': typeof PlaylistsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/create': typeof PlaylistsCreateRoute
  '/playlists/root': typeof PlaylistsRootRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/playlists/edit/$id': typeof PlaylistsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/create': typeof PlaylistsCreateRoute
  '/playlists/root': typeof PlaylistsRootRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/playlists/edit/$id': typeof PlaylistsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/library'
    | '/settings'
    | '/playlists/$id'
    | '/playlists/create'
    | '/playlists/root'
    | '/playlists'
    | '/playlists/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/library'
    | '/settings'
    | '/playlists/$id'
    | '/playlists/create'
    | '/playlists/root'
    | '/playlists'
    | '/playlists/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/library'
    | '/settings'
    | '/playlists/$id'
    | '/playlists/create'
    | '/playlists/root'
    | '/playlists/'
    | '/playlists/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  PlaylistsCreateRoute: typeof PlaylistsCreateRoute
  PlaylistsRootRoute: typeof PlaylistsRootRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PlaylistsEditIdRoute: typeof PlaylistsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/root': {
      id: '/playlists/root'
      path: '/playlists/root'
      fullPath: '/playlists/root'
      preLoaderRoute: typeof PlaylistsRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/create': {
      id: '/playlists/create'
      path: '/playlists/create'
      fullPath: '/playlists/create'
      preLoaderRoute: typeof PlaylistsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/edit/$id': {
      id: '/playlists/edit/$id'
      path: '/playlists/edit/$id'
      fullPath: '/playlists/edit/$id'
      preLoaderRoute: typeof PlaylistsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  PlaylistsIdRoute: PlaylistsIdRoute,
  PlaylistsCreateRoute: PlaylistsCreateRoute,
  PlaylistsRootRoute: PlaylistsRootRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PlaylistsEditIdRoute: PlaylistsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
