/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsRootRouteImport } from './routes/playlists/root'
import { Route as PlaylistsRecentRouteImport } from './routes/playlists/recent'
import { Route as PlaylistsIdRouteImport } from './routes/playlists/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRootRoute = PlaylistsRootRouteImport.update({
  id: '/playlists/root',
  path: '/playlists/root',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRecentRoute = PlaylistsRecentRouteImport.update({
  id: '/playlists/recent',
  path: '/playlists/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/recent': typeof PlaylistsRecentRoute
  '/playlists/root': typeof PlaylistsRootRoute
  '/playlists': typeof PlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/recent': typeof PlaylistsRecentRoute
  '/playlists/root': typeof PlaylistsRootRoute
  '/playlists': typeof PlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/recent': typeof PlaylistsRecentRoute
  '/playlists/root': typeof PlaylistsRootRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favourites'
    | '/import'
    | '/library'
    | '/settings'
    | '/playlists/$id'
    | '/playlists/recent'
    | '/playlists/root'
    | '/playlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favourites'
    | '/import'
    | '/library'
    | '/settings'
    | '/playlists/$id'
    | '/playlists/recent'
    | '/playlists/root'
    | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/favourites'
    | '/import'
    | '/library'
    | '/settings'
    | '/playlists/$id'
    | '/playlists/recent'
    | '/playlists/root'
    | '/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesRoute: typeof FavouritesRoute
  ImportRoute: typeof ImportRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  PlaylistsRecentRoute: typeof PlaylistsRecentRoute
  PlaylistsRootRoute: typeof PlaylistsRootRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/root': {
      id: '/playlists/root'
      path: '/playlists/root'
      fullPath: '/playlists/root'
      preLoaderRoute: typeof PlaylistsRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/recent': {
      id: '/playlists/recent'
      path: '/playlists/recent'
      fullPath: '/playlists/recent'
      preLoaderRoute: typeof PlaylistsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesRoute: FavouritesRoute,
  ImportRoute: ImportRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  PlaylistsIdRoute: PlaylistsIdRoute,
  PlaylistsRecentRoute: PlaylistsRecentRoute,
  PlaylistsRootRoute: PlaylistsRootRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
